package com.echopen.asso.echopen.echography_image_streaming.notifications;

import android.graphics.Bitmap;

/**
 * Created by lecoucl on 06/06/17.
 *
 * @class notification event sent to Application when a new image is generated by ImageStreamingService
 */

public class EchographyImageStreamingNotification {

    private Bitmap mImage; /* bitmap image to be displayed */

    /**
     * @brief constructor
     *
     * @param iImage bitmap image to be displayed
     */
    public EchographyImageStreamingNotification(Bitmap iImage){
        mImage = iImage;
    }

    /**
     * @brief getter
     *
     * @return bitmap image
     */
    public Bitmap getImage(){
        return mImage;
    }
}
