package com.echopen.asso.echopen.probe_communication.notifications;

/**
 * Created by lecoucl on 06/06/17.
 *
 * @class notification event sent to Application when a new image is generated by ImageStreamingService
 */

public class ProbeCommunicationWifiNotification {
    private ProbeCommunicationWifiNotificationState mState;

    public ProbeCommunicationWifiNotification(ProbeCommunicationWifiNotificationState iState){
        mState = iState;
    }

    public ProbeCommunicationWifiNotificationState getState(){
        return mState;
    }

}
