package com.echopen.asso.echopen.probe_communication.notifications;

import com.echopen.asso.echopen.probe_communication.commands.Request;

/**
 *
 * @class notification event sent to Application when a new image is generated by ImageStreamingService
 */

public class ProbeCommunicationSendRequestNotification {
    private Request mRequest;

    public ProbeCommunicationSendRequestNotification(Request iRequest){
        mRequest = iRequest;
    }

    public Request getRequest(){
        return mRequest;
    }

}
