package com.echopen.asso.echopen.probe_communication.notifications;

/**
 *
 * @class notification event sent to Application when a new image is generated by ImageStreamingService
 */

public class ProbeCommunicationWifiNotification {
    private WifiState mState;

    public ProbeCommunicationWifiNotification(WifiState iState){
        mState = iState;
    }

    public WifiState getState(){
        return mState;
    }

}
