package com.echopen.asso.echopen.probe_communication.notifications;

/**
 *
 * @class notification event sent to Application when a new image is generated by ImageStreamingService
 */

public class ProbeCommunicationSendBytesReplyNotification {
    private byte[] mReply;
    private int mReplySize;

    public ProbeCommunicationSendBytesReplyNotification(byte[] iReply, int iReplySize){
        mReply = iReply;
        mReplySize = iReplySize;
    }

    public byte[] getReply(){
        return mReply;
    }

    public int getReplySize(){return mReplySize; }

}
